/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    AButton: typeof import('ant-design-vue/es')['Button']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    FormCriaSolicitacao: typeof import('./src/components/FormCriaSolicitacao.vue')['default']
    FormCriaUsuario: typeof import('./src/components/FormCriaUsuario.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeScreen: typeof import('./src/components/HomeScreen.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabelaSolicitacoes: typeof import('./src/components/TabelaSolicitacoes.vue')['default']
    TabelaSolicitacoesUsuario: typeof import('./src/components/TabelaSolicitacoesUsuario.vue')['default']
    TelaCriaSolicitacao: typeof import('./src/components/TelaCriaSolicitacao.vue')['default']
    TelaCriaUsuario: typeof import('./src/components/TelaCriaUsuario.vue')['default']
    TelaSolicitacoes: typeof import('./src/components/TelaSolicitacoes.vue')['default']
  }
}
