/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ABadge: typeof import('ant-design-vue/es')['Badge']
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACalendar: typeof import('ant-design-vue/es')['Calendar']
    ACol: typeof import('ant-design-vue/es')['Col']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATimePicker: typeof import('ant-design-vue/es')['TimePicker']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    FormCriaHoraValida: typeof import('./src/components/FormCriaHoraValida.vue')['default']
    FormCriaSolicitacao: typeof import('./src/components/FormCriaSolicitacao.vue')['default']
    FormCriaUsuario: typeof import('./src/components/FormCriaUsuario.vue')['default']
    FormEditaHoras: typeof import('./src/components/FormEditaHoras.vue')['default']
    FormEditaHoraValida: typeof import('./src/components/FormEditaHoraValida.vue')['default']
    FormEditarSolicitacao: typeof import('./src/components/FormEditarSolicitacao.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    HomeScreen: typeof import('./src/components/HomeScreen.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabelaHoras: typeof import('./src/components/TabelaHoras.vue')['default']
    TabelaSolicitacoes: typeof import('./src/components/TabelaSolicitacoes.vue')['default']
    TabelaSolicitacoesUsuario: typeof import('./src/components/TabelaSolicitacoesUsuario.vue')['default']
    TelaCriaHoraValida: typeof import('./src/components/TelaCriaHoraValida.vue')['default']
    TelaCriaSolicitacao: typeof import('./src/components/TelaCriaSolicitacao.vue')['default']
    TelaCriaUsuario: typeof import('./src/components/TelaCriaUsuario.vue')['default']
    TelaEditaHoraValida: typeof import('./src/components/TelaEditaHoraValida.vue')['default']
    TelaEditaSolicitacao: typeof import('./src/components/TelaEditaSolicitacao.vue')['default']
    TelaHorasValidas: typeof import('./src/components/TelaHorasValidas.vue')['default']
    TelaSolicitacoes: typeof import('./src/components/TelaSolicitacoes.vue')['default']
  }
}
